simplify

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -88,6 +88,32 @@ setup_linux() {
     fi
 }
 
+install_lsp() {
+    echo 'installing lsp servers'
+
+    if [[ $(uname -s) == Darwin ]]; then
+        brew install pipx node
+    else
+        sudo apt-get install -y clangd pipx nodejs npm
+    fi
+
+    pipx install pyright
+    npm install -g typescript-language-server
+
+    local jdtls_dir="$XDG_DATA_HOME/eclipse.jdt.ls"
+    if [[ ! -d $jdtls_dir ]]; then
+        git clone https://github.com/eclipse-jdtls/eclipse.jdt.ls "$jdtls_dir"
+    else
+        git -C "$jdtls_dir" fetch --tags
+    fi
+
+    local latest_tag
+    latest_tag=$(git -C "$jdtls_dir" tag --sort=-version:refname | head -1)
+    git -C "$jdtls_dir" checkout "$latest_tag"
+
+    "$jdtls_dir/mvnw" -f "$jdtls_dir/pom.xml" clean verify -DskipTests=true
+}
+
 configure_shell() {
     if [[ $SHELL == */fish ]]; then
         echo 'default shell is already fish'
@@ -120,6 +146,7 @@ main() {
     else
         setup_linux
     fi
+    install_lsp || echo 'warning: install_lsp failed, continuing' >&2
     configure_shell
 }
 
