zsh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,15 +6,15 @@ link_dotfiles() {
     mkdir -p "${XDG_CONFIG_HOME:-"$HOME/.config"}"
 
     echo '> linking dotfiles'
-    ln -sfn $(pwd)/fish ~/.config/fish
     ln -sfn $(pwd)/nvim ~/.config/nvim
+    ln -sfn $(pwd)/.zshrc ~/.zshrc
     ln -sfn $(pwd)/.gitignore ~/.gitignore
     ln -sfn $(pwd)/.psqlrc ~/.psqlrc
 }
 
 setup_linux() {
     echo '> installing essential packages'
-    sudo apt-get update && sudo apt-get install -y curl git fish watch neovim tree ncdu htop ripgrep jq
+    sudo apt-get update && sudo apt-get install -y curl git zsh neovim tree ncdu htop ripgrep jq
 }
 
 setup_mac() {
@@ -25,7 +25,7 @@ setup_mac() {
         eval "$(/opt/homebrew/bin/brew shellenv)"
     }
     echo '> installing essential packages'
-    brew update && brew install fish watch neovim tree ncdu htop ripgrep jq font-ubuntu-sans-mono
+    brew update && brew install watch neovim tree ncdu htop ripgrep jq font-ubuntu-sans-mono
 }
 
 config_git() {
@@ -36,16 +36,19 @@ config_git() {
     git config --global diff.tool nvimdiff
     git config --global merge.tool nvimdiff
     git config --global mergetool.keepBackup false
+
+    echo '> downloading git-prompt'
+    curl -fsSL https://raw.githubusercontent.com/git/git/refs/heads/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
 }
 
 config_shell() {
-    [ "${SHELL##*/}" = fish ] && { echo '* default shell is already fish'; return 0; }
-    fish_path=$(command -v fish || true)
-    [ -n "$fish_path" ] || { echo '! fish not found in path' >&2; return 1; }
+    [ "${SHELL##*/}" = zsh ] && { echo '* default shell is already zsh'; return 0; }
+    zsh_path=$(command -v zsh || true)
+    [ -n "$zsh_path" ] || { echo '! zsh not found in path' >&2; return 1; }
 
-    echo '> changing default shell to fish'
-    grep -qxF "$fish_path" /etc/shells || echo "$fish_path" | sudo tee -a /etc/shells
-    chsh -s "$fish_path"
+    echo '> changing default shell to zsh'
+    grep -qxF "$zsh_path" /etc/shells || echo "$zsh_path" | sudo tee -a /etc/shells
+    chsh -s "$zsh_path"
     echo '* please log out and log back in for shell change to take effect'
 }
 
